=== despley/BrownBagXML/XmlFormat/XmlPartyInvites.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema id="XmlPartyInvites" targetNamespace="http://tempuri.org/XmlPartyInvites.xsd" elementFormDefault="qualified"
           xmlns="http://tempuri.org/XmlPartyInvites.xsd" xmlns:mstns="http://tempuri.org/XmlPartyInvites.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="XmlParty">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Party" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Message" type="xs:string" />
              <xs:element name="Invite">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Attendee" maxOccurs="unbounded" type="attendeeType" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="attendeeType">
    <xs:choice>
      <xs:element name="TelephoneCall" type="xs:string" />
      <xs:element name="SmokeSignal">
        <xs:complexType></xs:complexType>
      </xs:element>
      <xs:element name="SnailMail" type="postageType" />
    </xs:choice>
    <xs:attribute name="id" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:token">
              <xs:length fixed="true" value="36" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="postageType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="class" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="FirstClass" />
              <xs:enumeration value="SecondClass" />
              <xs:enumeration value="HandDelivered" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== despley/BrownBagXML/XmlPartyParserTests/XmlPartyInvites.xml
<?xml version="1.0" encoding="utf-8"?>

<XmlParty xmlns="http://tempuri.org/XmlPartyInvites.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://tempuri.org/XmlPartyInvites.xsd XmlPartyInvites.xsd">
  <Party id="75aaae10-b42f-49db-9cfe-22322e3943a5">
    <Message>
      Hello, please come to my party - it will be great
    </Message>
    <Invite>
      <Attendee id="661d4e8f-79d2-4127-a791-7a1c1d27a1d2">
        <TelephoneCall>01292488599</TelephoneCall>
      </Attendee>
      <Attendee id="1a4ebb6a-0a7e-4bde-aca3-f158d856c988">
        <SnailMail class="FirstClass">
          18 Baker St, London, W12 4TF
        </SnailMail>
      </Attendee>
      <Attendee id="ad13157f-f683-4e13-a4f9-a15f47dae398">
        <SmokeSignal />
      </Attendee>
      <Attendee id="661d4e8f-79d2-4127-a791-7a1c1d27a1d2">
        <TelephoneCall>0129248599</TelephoneCall>
      </Attendee>
      <Attendee id="e0e38356-0c8a-430b-add5-8c59775c545f">
        <TelephoneCall>02488599</TelephoneCall>
      </Attendee>
      <Attendee id="7fd48a91-7c52-4de6-b155-7b62ec23002c">
        <SmokeSignal />
      </Attendee>
      <Attendee id="032180d5-1f3b-4e42-bd12-60609f2e61c2">
        <TelephoneCall>01292488599</TelephoneCall>
      </Attendee>
      <Attendee id="3ca9b05f-d686-4258-b40a-ab57f0518f00">
        <SnailMail class="SecondClass">
          18 Baker St, London, W12 4TF
        </SnailMail>
      </Attendee>
      <Attendee id="eb85302a-ab18-4d87-a434-6cae9d450c2c">
        <SnailMail class="FirstClass">
          19 Baker St, London, W12 4TF
        </SnailMail>
      </Attendee>
      <Attendee id="eb85302a-ab18-4d87-a434-6cae9d450e2c">
        <SnailMail class="HandDelivered">
          20 Baker St, London, W12 4TF
        </SnailMail>
      </Attendee>
    </Invite>
  </Party>
  <Party id="731db09a-39be-49d8-a75a-bddab653e20d">
    <Message>
      This will be a rubbish party - but you can come anyway
    </Message>
    <Invite>
      <Attendee id="661d4e8f-79d2-4127-a791-7a1c1d27a1d3">
        <TelephoneCall>01292488599</TelephoneCall>
      </Attendee>
      <Attendee id="1a4ebb6a-0a7e-4bde-aca3-f158d856c988">
        <SnailMail class="FirstClass">
          18 Baker St, London, W12 4TF
        </SnailMail>
      </Attendee>
      <Attendee id="ad13157f-f683-4e13-a4f9-a15f47dae398">
        <SmokeSignal />
      </Attendee>
      <Attendee id="661d4e8f-79d2-4127-a791-7a1c1d27a1d2">
        <TelephoneCall>0129248599</TelephoneCall>
      </Attendee>
      <Attendee id="e0e38356-0c8a-430b-add5-8c59775c545f">
        <TelephoneCall>02488599</TelephoneCall>
      </Attendee>
      <Attendee id="7fd48a91-7c52-4de6-b155-7b62ec23002c">
        <SmokeSignal />
      </Attendee>
      <Attendee id="032180d5-1f3b-4e42-bd12-60609f2e61c3">
        <TelephoneCall>01292488599</TelephoneCall>
      </Attendee>
      <Attendee id="3ca9b05f-d686-4258-b40a-ab57f0518f00">
        <SnailMail class="SecondClass">
          18 Baker St, London, W12 4TF
        </SnailMail>
      </Attendee>
      <Attendee id="eb85302a-ab18-4d87-a434-6cae9d450c2c">
        <SnailMail class="FirstClass">
          19 Baker St, London, W12 4TF
        </SnailMail>
      </Attendee>
      <Attendee id="eb85302a-ab18-4d87-a434-6cae9d450e2c">
        <SnailMail class="HandDelivered">
          20 Baker St, London, W12 4TF
        </SnailMail>
      </Attendee>
    </Invite>
  </Party>
</XmlParty>
